Proposal： CloudEvents Spec in Chinese
cloudevents/spec pull request #899
Opened 2021-11-10 00:16 UTC by JieDing

## Proposed Changes

I'd like to translate a Chinese Version Specification based on the English one  in order to lower the difficulty of reading and accelerate the spread of CloudEvents for Chinese developers.
-Currently, these documents below have been done based on the spec v1.0.1 and v1.0:
-README.md, primer.md and spec.md.
-other documents in both versions can be started later if necessary.

2021-11-11 02:07 UTC, JieDing commented
@duglin

2021-11-11 11:55 UTC, duglin commented
It's on the agenda for the call today.
Also, can you re-base, I think you have old commits in your list

2021-11-11 12:41 UTC, JieDing commented
> It's on the agenda for the call today. Also, can you re-base, I think you have old commits in your list

Thanks a lot for replying. I'll re-base it asap.

2021-11-11 13:56 UTC, duglin commented
@JieDing the problem isn't the files, the problem is you have old (other people's) commits as part of this PR. You should rebase on top of the latest version of the branch (`main`) and only include your commits

2021-11-11 17:44 UTC, cathyhongzhang commented on Chinese-Manual/README.md
> +
This section describes why we need CloudEvents in Chinese. Suggest adding a section title (both English and Chinese) to this section.

2021-11-11 17:53 UTC, cathyhongzhang commented on Chinese-Manual/spec_CN.md
> +请参阅 CloudEvents  [入门文档](primer_CN.md)。
These links are broken when I clicked them. Not sure if the issue is specific to me.

2021-11-16 02:21 UTC, duglin commented on Chinese-Manual/README.md
> +| CloudEvents                   |          [v1.0.1](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md)          |            [master](https://github.com/cloudevents/spec/blob/master/spec.md)
I think the links here are old since the branch is now "main"

2021-11-16 02:24 UTC, duglin commented
@JieDing thanks a ton for doing this. We discussed this on last week's call and there were just a few comments:
- are you planning on keeping these documents up to date as we make changes?
- can you put them under `cloudevents/translated/zh-cn/`  ? Is "zh-cn" the right code?

2021-11-16 02:58 UTC, JieDing commented
> * zh-cn


> @JieDing thanks a ton for doing this. We discussed this on last week's call and there were just a few comments:
> 
> * are you planning on keeping these documents up to date as we make changes?
> * can you put them under `cloudevents/translated/zh-cn/`  ? Is "zh-cn" the right code?

* Yes, I'll keep translating documents as you make changes. 
* BTY,  please @me to let me know if there are some documents you prefer to translate first.
* Documents would be translated based on my schedule if there is no specified order of translation.
* I'll put documents under `cloudevents/translated/zh-cn/` later. "zh-cn" is the right code.

2021-11-17 00:38 UTC, JieDing commented
This PR seems doesn't meet the verify checker as it [said](https://github.com/cloudevents/spec/runs/4228594241?check_suite_focus=true) "Can't find section '#XXX' in ./cloudevents/translated/zh-cn/primer_CN.md" where XXX are Chinese characters.
I was wondering if the href checker doesn't support Chinese since I can find and jump to those sections in my repository. 
@duglin

2021-11-17 02:04 UTC, ifplusor requested changes

2021-11-20 23:28 UTC, duglin commented
@JieDing did you want to address the comments made?

2021-11-22 06:07 UTC, JieDing commented
> @JieDing did you want to address the comments made?
I've made some changes to see if it's gonna address the problem

2021-11-29 23:31 UTC, duglin commented on cloudevents/translated/zh-cn/README_CN.md
> +由于并非所有事件生产者都默认生产符合CloudEvents规范的事件，因此可以用[CloudEvents适配器](https://github.com/cloudevents/spec/blob/main/cloudevents/adapters.md)
I kind of like the original version better.

2021-11-29 23:37 UTC, duglin commented
@JieDing thanks! I'll add it to this week's agenda for final approaval

2021-11-29 23:47 UTC, JieDing commented
> @JieDing thanks! I'll add it to this week's agenda for final approaval

I do feel happy to make a contribution to CloudEvents. Just let me know if anything needs to be modified.

2021-12-06 19:20 UTC, duglin commented
Approved on the 12/02 call
thanks again @JieDing !!

2021-12-06 19:20 UTC, merged